[package]
name = "luminance_procedural_world"
version = "0.1.0"
authors = ["twetzel59 <twetzel59@gmail.com>"]

[dependencies.luminance-glfw]
git = "https://github.com/twetzel59/luminance-glfw.git"

[dependencies]
glfw = "0.16"
luminance = "0.24.0"
